# syntax=docker/dockerfile:1

FROM debian:bookworm-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		ca-certificates curl osmium-tool \
		python3 python3-psycopg2 \
		postgresql-client \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app
