XMULT.AB:
 1: DEC A        ---|                ---|
 2: INC D           |---Increment D     |
 3: ZER A     5     |   A number of     |
 4: GTO  1       ---|   times           |---A gets A*B when D is
 5: DEC D        ---|                   |   initially zero
 6: CAL XADD        |---Add B to A      |
 7: ZER D     9     |   D number of     |
 8: GTO  5       ---|   times        ---|
 9: END          
11:              PURPOSE: compute the product of two given integers.
12:              INPUT:   register [A] contains a positive integer;
13:                       register [B] contains an integer
14:                       (assume that register [D] contains 0).
15:              OUTPUT:  register [A] gets the product of registers
16:                       [A] and [B].
18:              (EXP.AB calls this program, and it in turn calls
19:               XADD.AB)
99: END          
