#!/usr/bin/env python3
"""Rebuild FTPDAT from the dumped MacLisp heap in TS FTP.

Reads ../ts.ftp.dis (dis10 -Wits -Fpdump output), finds every symbol whose property list
carries LOCATION and LAST-UPDATE (one per DEFINE-SITE), decodes the values and writes
ftpdat.json. Run from this directory: python3 extract.py
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
M = {}
for line in open(HERE.parent / "ts.ftp.dis"):
    m = re.match(r"^([0-7]{6}):\s+([0-7]{12})", line)
    if m:
        M[int(m.group(1), 8)] = int(m.group(2), 8)

L = lambda w: w >> 18
R = lambda w: w & 0o777777
T = 0o75000                      # the symbol T in this Lisp
FIXNUMS = range(0o105000, 0o107000)  # preallocated small fixnums: value = addr - 106001
MORE_THAN = 0o75466              # the marker used in (> . n) costs; prints as "more than"


def chars(w):
    return "".join(chr((w >> (29 - 7 * k)) & 127) for k in range(5))


def pname(cell):
    out, seen = [], set()
    while cell and cell in M and cell not in seen:
        seen.add(cell)
        w = M[cell]
        out.append(chars(M.get(L(w), 0)))
        cell = R(w)
    return "".join(out).replace("\0", "")


def symname(a):
    """A symbol's name: header LH -> SY2 block, whose second word's RH is the pname list."""
    if a not in M:
        return None
    sy2 = L(M[a])
    if sy2 not in M or sy2 + 1 not in M or (M[sy2] >> 27) != 0o777:
        return None
    t = pname(R(M[sy2 + 1]))
    return t if t and all(32 <= ord(c) < 127 or c in "\r\n\t" for c in t) else None


def flonum(a):
    w = M.get(a)
    if w is None or a in SYMS or w >> 35 or L(w) in M or not L(w):
        return None
    e = (w >> 27) & 0o377
    if not 0o170 <= e <= 0o220:
        return None
    return round((w & 0o777777777) / 2**27 * 2 ** (e - 128), 4)


SYMS = {a: n for a in M if (n := symname(a))}


def obj(a, depth=0):
    if depth > 24:
        return None
    if a == 0:
        return None
    if a == T:
        return True
    if a in FIXNUMS:
        return a - 0o106001
    if a == MORE_THAN:
        return ">"
    if a in SYMS:
        return SYMS[a]
    f = flonum(a)
    if f is not None:
        return f
    if a not in M:
        return None
    out, x = [], a
    while x and x in M and x != T and x not in FIXNUMS and x not in SYMS and flonum(x) is None:
        out.append(obj(L(M[x]), depth + 1))
        x = R(M[x])
    if x:  # dotted pair: (a . b) ranges and (> . n)
        return {"range": [out[0] if len(out) == 1 else out, obj(x, depth + 1)]}
    return out


def plist(s):
    out, pl = [], R(M[s])
    while pl and pl in M and R(M[pl]) in M:
        ind = SYMS.get(L(M[pl]))
        pl = R(M[pl])
        out.append((ind, L(M[pl])))
        pl = R(M[pl])
    return out


sites = {}
for s, name in SYMS.items():
    props = plist(s)
    keys = {k for k, _ in props}
    if {"LOCATION", "LAST-UPDATE"} <= keys:
        site = {}
        for k, v in props:
            val = obj(v)
            if k in ("MENU", "SMALL", "MEDIUM", "LARGE") and isinstance(val, list):
                val = [x for x in val if isinstance(x, str)]
            site[k.lower()] = val
        sites[name] = site

data = json.dumps(dict(sorted(sites.items())), indent=1)
(HERE / "ftpdat.json").write_text(data + "\n")
# The same data as a script, so index.html also works opened straight from disk (file:// can't fetch).
(HERE / "ftpdat.js").write_text("// Generated by extract.py from TS FTP; same data as ftpdat.json.\nwindow.FTPDAT = " + data + ";\n")
print(f"{len(sites)} sites -> ftpdat.json, ftpdat.js")
