import { assemble } from "./asm.js";
import { assembleAs7 } from "./asm/as7.js";
import { attachScan, type ScanLines, type SourceMap, sourceFromAsm, sourceFromListing } from "./source.js";

const SCANS = "https://raw.githubusercontent.com/SimHacker/WillWrightShowForFood/main/characters/heinz-lemke/sources/pixie-assembler-listing-1972/pages";
const scan = (n: number): string => `${SCANS}/page-${String(n).padStart(3, "0")}.png`;

/**
 * SYMELEC's three maps over the same 4,674 words: Heinz's 1972 listing as printed, the Cambridge
 * source transcribed from it, and that source translated to as7. All three assemble to one image.
 * With `scan` (scanmap/symelec-lines.json), every line that assembled a word knows its rectangles
 * on the scanned page.
 */
export function symelecSources(texts: { listing: string; cambridge: string; as7: string; scan?: ScanLines }): SourceMap[] {
	const cam = assemble([{ name: "symelec.asm", text: texts.cambridge }], { dialect: "cambridge", origin: 0o22 });
	const as7 = assembleAs7([{ name: "symelec.s", text: texts.as7 }], { base: 0 });
	const maps = [
		// Listing page 1 is the third PDF page, page-002.png.
		sourceFromListing(texts.listing, { id: "listing", label: "1972 listing", kind: "listing", dialect: "cambridge", origin: "Titan lineprinter, 12 Feb 1972, HL1470", scanUrl: (p) => scan(p + 1) }),
		sourceFromAsm(cam, { id: "cambridge", label: "Cambridge source", kind: "source", dialect: "cambridge", origin: "symelec.asm, transcribed from the scans", scanUrl: scan }),
		sourceFromAsm(as7, { id: "as7", label: "as7 translation", kind: "translation", dialect: "as7", origin: "symelec.s, generated by scripts/translate-cambridge.mjs", scanUrl: scan }),
	] as [SourceMap, SourceMap, SourceMap];
	if (texts.scan) attachScan(maps[0], maps.slice(1), texts.scan, scan);
	return maps;
}
