#!/usr/bin/env python3
"""Micro-SHRDLU (UMD CogSci Courseware, 1990) grammar: disk to YAML, a parser, a verifier.

    python3 packages/mshrdlu/scripts/mshrdlu.py convert          # disk -> grammar.yml
    python3 packages/mshrdlu/scripts/mshrdlu.py parse "put the big red cube in the box"
    python3 packages/mshrdlu/scripts/mshrdlu.py verify           # examples.yml + rules-vs-compiled report

The program's grammar ships as data: MSHRDLU.MAP numbers 119 pieces, each a
transition network (.NET, type N) or a word list (.LEX, type L). Several pieces
can serve one nonterminal (S is S.NET .. S18.NET). A .NET file is

    <states> <name> then per state: <arc count>, then <arc count> lines "<piece> <next>"

where <piece> is a 1-based MAP index, piece 0 with a next state is an empty arc,
and "0 0" marks the accepting state. MSHRDLU.GRA is the rewrite-rule listing the
help screen prints; it is documentation and has drifted from the compiled pieces.
verify reports the drift. The parser runs the compiled pieces, like PTRACE.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parents[1]
ROOT = HERE.parents[1]
DISK = ROOT / "characters/christopher-cherniak/sources/mshrdlu/disk/MSHRDLU"
DISK_REL = "characters/christopher-cherniak/sources/mshrdlu/disk/MSHRDLU"
SKIP = "skip"


def lines(name: str) -> list[str]:
    raw = (DISK / name).read_bytes().decode("latin-1").replace("\x1a", "")
    return [l.strip() for l in raw.replace("\r\n", "\n").split("\n")]


def dos_name(stem: str, ext: str) -> str:
    return f"{stem[:8]}.{ext}"


def read_map() -> list[tuple[str, str, str]]:
    ls = [l for l in lines("MSHRDLU.MAP") if l]
    n = int(ls[0])
    entries = [tuple(l.split()) for l in ls[1:n + 1]]
    assert len(entries) == n
    return entries


def read_net(fname: str) -> dict:
    tok = " ".join(lines(fname)).split()
    n, name, i = int(tok[0]), tok[1], 2
    states = []
    for _ in range(n):
        k = int(tok[i]); i += 1
        arcs = [(int(tok[i + 2 * j]), int(tok[i + 2 * j + 1])) for j in range(k)]
        i += 2 * k
        states.append(arcs)
    return dict(name=name, states=states)


def read_lex(fname: str) -> list[str]:
    ls = [l for l in lines(fname) if l]
    return ls[1:int(ls[0]) + 1]


def read_gra() -> dict[str, list[list[str] | set]]:
    text = "\n".join(l for l in lines("MSHRDLU.GRA") if not l.startswith("*") and l != "end")
    rules: dict[str, list] = {}
    for m in re.finditer(r"(\w+)\s*->\s*(\[[^\]]*\]|[^\n]*)", text):
        lhs, rhs = m[1], m[2].strip()
        if rhs.startswith("["):
            rules.setdefault(lhs, []).append(set(rhs[1:-1].split()))
        else:
            rules.setdefault(lhs, []).append(rhs.split())
    return rules


def compile_disk() -> dict:
    entries = read_map()
    pieces = {}
    for idx, (nt, fname, kind) in enumerate(entries, 1):
        f = dos_name(fname, "NET" if kind == "N" else "LEX")
        if kind == "N":
            net = read_net(f)
            states = {}
            for s, arcs in enumerate(net["states"], 1):
                if arcs == [(0, 0)]:
                    states[s] = "accept"
                else:
                    states[s] = {(SKIP if p == 0 else entries[p - 1][1]): t for p, t in arcs}
            pieces[fname] = dict(index=idx, serves=nt, kind="network", file=f, states=states)
        else:
            pieces[fname] = dict(index=idx, serves=nt, kind="words", file=f, words=read_lex(f))
    used = {p["file"] for p in pieces.values()} | {"MSHRDLU.MAP"}
    orphans = sorted(p.name for p in DISK.iterdir() if p.suffix.upper() in (".NET", ".LEX") and p.name not in used)
    return dict(pieces=pieces, orphans=orphans)


def reads(piece: dict, pieces: dict) -> str:
    """A linear network as a rule body: '(ART) (SIZEWORD) (COLORWORD) OBJWORD'."""
    out = []
    for s, arcs in piece["states"].items():
        if arcs == "accept":
            continue
        names = []
        for k in arcs:
            if k != SKIP:
                n = pieces[k]["serves"]
                if n not in names:
                    names.append(n)
        body = "|".join(names)
        out.append(f"({body})" if SKIP in arcs else body)
    return " ".join(out)


def q(s: str) -> str:
    return '"' + s.replace('"', '\\"') + '"'


def grammar_yaml(g: dict) -> str:
    pieces = g["pieces"]
    out = ["# Micro-SHRDLU's compiled grammar, from the course disk: " + DISK_REL,
           "# Generated by packages/mshrdlu/scripts/mshrdlu.py convert. Order = MSHRDLU.MAP order.",
           "# A network's states map piece -> next state; skip = empty arc; accept ends the piece.",
           "# Arcs name pieces (files), not nonterminals: PUTS and PUTS1 both serve PUTS.",
           "# reads: is the network written back as a rewrite rule, for comparison with MSHRDLU.GRA.",
           "",
           "id: mshrdlu-grammar",
           "credits:",
           "  - Christopher Cherniak, concept and supervision",
           "  - Andy Evans, John Ornelas, Robert Winkler, programmers",
           "  - Micro-SHRDLU Preliminary Version 1990, U of MD CogSci Instructional Software Project",
           "start: SEN",
           f"orphans: [{', '.join(g['orphans'])}]  # on the disk, not named by MSHRDLU.MAP, never loaded",
           "pieces:"]
    for name, p in pieces.items():
        out.append(f"  {name}:  # {p['index']}: {p['file']}")
        out.append(f"    serves: {p['serves']}")
        if p["kind"] == "words":
            out.append("    words: [" + ", ".join(q(w) for w in p["words"]) + "]")
        else:
            out.append(f"    reads: {q(reads(p, pieces))}")
            out.append("    states:")
            for s, arcs in p["states"].items():
                if arcs == "accept":
                    out.append(f"      {s}: accept")
                else:
                    out.append(f"      {s}: {{ " + ", ".join(f"{k}: {t}" for k, t in arcs.items()) + " }")
    return "\n".join(out) + "\n"


def tokenize(sentence: str) -> list[str]:
    return re.sub(r"[.,?!;:\"()]", " ", sentence.upper()).split()


def parse(grammar: dict, sentence: str) -> list:
    pieces = grammar["pieces"]
    serving: dict[str, list[str]] = {}
    for name, p in pieces.items():
        serving.setdefault(p["serves"], []).append(name)
    toks = tokenize(sentence)

    def piece(name: str, i: int):
        p = pieces[name]
        if "words" in p:
            for w in p["words"]:
                ws = w.split()
                if toks[i:i + len(ws)] == ws:
                    yield i + len(ws), (p["serves"], w)
            return
        yield from walk(p, 1, i, [])

    def walk(p: dict, s: int, i: int, kids: list):
        arcs = p["states"][s]
        if arcs == "accept":
            yield i, (p["serves"], kids)
            return
        for k, t in arcs.items():
            if k == SKIP:
                yield from walk(p, t, i, kids)
            else:
                for j, tree in piece(k, i):
                    yield from walk(p, t, j, kids + [tree])

    start = grammar["start"]
    return [tree for name in serving[start] for j, tree in piece(name, 0) if j == len(toks)]


def show(tree, depth: int = 0) -> str:
    name, body = tree
    pad = "  " * depth
    if isinstance(body, str):
        return f"{pad}{name}: {body}"
    return "\n".join([f"{pad}{name}"] + [show(k, depth + 1) for k in body])


def drift(g: dict) -> list[str]:
    pieces = g["pieces"]
    gra = read_gra()
    compiled: dict[str, list] = {}
    for p in pieces.values():
        if p["kind"] == "words":
            compiled.setdefault(p["serves"], []).append(set(p["words"]))
        else:
            compiled.setdefault(p["serves"], []).append(reads(p, pieces).split())
    notes = []
    for nt in sorted(set(gra) | set(compiled)):
        a, b = gra.get(nt), compiled.get(nt)
        if a is None:
            notes.append(f"{nt}: compiled only")
            continue
        if b is None:
            notes.append(f"{nt}: in MSHRDLU.GRA, never compiled")
            continue
        wa = set().union(*[x for x in a if isinstance(x, set)]) if any(isinstance(x, set) for x in a) else None
        wb = set().union(*[x for x in b if isinstance(x, set)]) if any(isinstance(x, set) for x in b) else None
        if wa is not None and wb is not None and wa != wb:
            extra, gone = sorted(wb - wa), sorted(wa - wb)
            notes.append(f"{nt}: words" + (f" +{' '.join(extra)}" if extra else "") + (f" -{' '.join(gone)}" if gone else ""))
        ra = sorted(" ".join(x) for x in a if isinstance(x, list))
        rb = sorted(" ".join(x) for x in b if isinstance(x, list))
        if ra != rb and not (nt == "S" and set(ra) >= set(rb)):
            notes.append(f"{nt}: rules GRA {ra} vs compiled {rb}")
    s_gra = {x[0] for x in gra["S"]}
    s_net = {x[0] for x in compiled["S"]}
    for miss in sorted(s_gra - s_net):
        notes.append(f"S -> {miss}: in MSHRDLU.GRA, no compiled S piece")
    return notes


def convert() -> None:
    g = compile_disk()
    (HERE / "grammar.yml").write_text(grammar_yaml(g))
    n = sum(1 for p in g["pieces"].values() if p["kind"] == "network")
    print(f"wrote grammar.yml: {len(g['pieces'])} pieces ({n} networks), {len(g['orphans'])} orphans")


def verify() -> int:
    g = yaml.safe_load((HERE / "grammar.yml").read_text())
    ex = yaml.safe_load((HERE / "examples.yml").read_text())
    fails = 0
    for e in ex["examples"]:
        trees = parse(g, e["say"])
        got = trees[0][1][-1][1][0][0] if trees else None
        ok = bool(trees) == e["parses"] and (not e.get("sentence") or got == e["sentence"])
        fails += not ok
        print(f"{'ok  ' if ok else 'FAIL'} {e['say']!r}: " + (f"{len(trees)} parse(s), {got}" if trees else "no parse"))
    print("\nMSHRDLU.GRA vs compiled pieces:")
    for n in drift(compile_disk()):
        print("  " + n)
    print("all ok" if not fails else f"{fails} failed")
    return 1 if fails else 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "verify"
    if cmd == "convert":
        convert()
    elif cmd == "parse":
        gr = yaml.safe_load((HERE / "grammar.yml").read_text())
        ts = parse(gr, " ".join(sys.argv[2:]))
        print(show(ts[0]) if ts else "I'm sorry, I didn't understand that.")
        if len(ts) > 1:
            print(f"({len(ts)} parses)")
    elif cmd == "verify":
        sys.exit(verify())
    else:
        print(__doc__)
        sys.exit(2)
