" rsppix.asm, Cambridge 1972, in as7: generated by scripts/translate-cambridge.mjs, do not edit.
"  ---- scan page 113 ----
" RSPPIX
.=022
rsetup:
0                                   " SETUP PACKAGE
lac rbeg
dac rfree
dac rop                             " FORM FREELIST
tad rlit023
dac i rop
and rlit022
sad rendres
skp
jmp .-06                            " LOOP
lac rbot
dac rtop+01                         " CLEAR NAME LIST
law rsavins
jms rinit
jms rsetup1
jmp i rsetup
rsetup1:
0
lac rlpbeg                          " INITIAL LOP AND LINK STAKS
dac rlop
lac rlkbeg
dac rlink
law rel
jms rinit
law rel1
jms rinit
law rnm
jms rinit
law rsavsub
jms rinit
law rpoint
jms rinit
law rline
jms rinit
law rsbpi
jms rinit
law rinst
jms rinit
law rpbdm
jms rinit
law rsymb
jms rinit
jmp i rsetup1
rerr: 0
hlt                                 " STACKS TO SHORT OR ?
dac rnote+05
jmp rerrmeb
0                                   " RTN TO SET OP, OP 1
dac rop
"  ---- scan page 114 ----
lac i rop
jms rcar+07
jmp .+014
rop: 0                              " LAW X
0                                   " CONTENTS OF X
0                                   " )
0                                   " )
0                                   " )
0                                   " ) WORKING SPACE
0                                   " USED ONLY IN FLST
0                                   " )WORKING SPACE
0                                   " )FOR
0                                   " )GARBAGE COLLECTOR
0                                   " )
lac i rop+01
and rlit021
sza
jms rerr                            " ERROR IF BLOCK DATA
lac rop+01
jmp i rop-05
rflst:
0                                   " FREE AN ITEM
lac rop+01
dac rop+06
lac rfree
sad rend
jms rlim                            " GARBAGE COLLECT
tad rlit020
sad rop+01
jmp .+016                           " IF CONSECUTIVE
sad rop+06
jmp . 013
tad rlit017
dac rop+06
xor rlit016
dac i rop+01
lac i rfree
and rlit022
dac rfree                           " ADVANCE FREE
lac rlit015
dac i rop+06                        " SET NIL
jmp rflst+03                        " LOOP TO TRY AGAIN
dac rop+01
dac rop+06                          " SAVE LAST ADDRESS
isz rop+06
lac i rfree
and rlit022
dac rfree                           " ADVANCE FREE
lac rlit015
dac i rop+01
dac i rop+06                        " SET NIL
jmp i rflst                         " EXIT WHEN ITEM CHAINED TO OP
"  ---- scan page 115 ----
rgetsp: 0
dac rop
lac rel1
dac i rop                           " IN CASE OF IMMEDIATE GARBAGE COLLECTION
lac rfree
sad rend
jms rlim                            " GARBAGE COLLECT
tad rlit015
dac rop+01
dac i rop
lac i rfree
and rlit022
dac rfree
lac rlit015
dac i rop+01                        " SET NIL
jms rflst                           " FREE AN ITEM
lac rop+01
dac i rop                           " ATTACH NAME
and i+jms+rgetsp
rinit: 0
jms rgetsp
lac rop
dac i rtop+01
isz rtop+01
lac rtop
sad rtop+01
jms rerr                            " NO ROOM FOR MORE NAMES
lac rop+01
and i+jms+rinit
rcdr:
0
jms rop-05                          " SAVE NAME
tad rlit017
dac rop+06                          " IN CASE NONITEM
jms rcar+07                         " TRUE ADDRESS OF CDR
lac rlit015
sad i rop+01
skp                                 " HERE IF CDR NIL
jmp . 04
lac rop+06
dac rop+01
jms rflst
lac rop+01
dac i rop                           " ATTACH NAME
lac rop
jmp i rcdr
rcar:
0
jms rop-05
lac i rop+01
"  ---- scan page 116 ----
jms rcar+07
dac i rop                           " MOVE NAME
lac rop
jmp i rcar
0                                   " SET OP+1 WITH ADDRESS FROM AC AND MS 5 BITS 00100
and rlit022                         "  AND MOVE TO NEXT ITEM IF ON NONITEM
tad rlit015
dac rop+01
lac i rop+01
spa
jmp .-05                            " DO AGAIN IF ON NONITEM
lac rop+01                          " PRESERVE AC
and i+jms+rcar+07
rpush:
0                                   " PUSH DOWN (LISTNAME
jms rop-05
tad rlit017
dac rel1                            " PREVENT TAIL BEING SWEPT UP IF GARBAGE COLLECTED
lac i rop+01
dac rop 02                          " SAVE ITEM
jms rflst                           " MAKE SPACE FOR NEW ITEM
lac rop 02
dac i rop+01
lac rop+01
dac i rop
isz rop+01
jms rflst                           " MAKE MORE SPACE
lac rop 02
dac i rop+01                        " COPY ITEM
lac rel1
xor rlit016
dac i rop+06                        " JOIN UP
lac rop
jmp i rpush
rpop:
0                                   " POP UP (LIST NAME
dac rop
lac i rop
dac rop 02                          " SAVE NAME
lac rop
jms rcdr
lac rop+01
xor rlit016
dac i rop 02                        " JOIN UP
lac rop
jmp i rpop
rstak: 0                            " OPERAND TO STACK
and rlit022
dac rop+03
isz rlop
lac rlop
sad rlkbeg
"  ---- scan page 117 ----
jms rerr
lac rop+03
dac i rlop
jmp i rstak
runstak: 0                          " OPERAND FROM STACK
lac i rlop
dac rop+03
lac rlop
sad rlpbeg
jms rerr
tad rlit014
dac rlop
lac rop+03
jmp i runstak
renter:
0                                   " ENTER SUBROUTINE (NAME ENTER
dac rop+03                          " SAVE ENTRY POINT
isz rlink
lac rlink
sad rlkend
jms rerr
lac renter
and rlit022
dac i rlink                         " SAVE LINK
jmp i rop+03                        " ENTER SUBROUTINE
rexit:
lac i rlink                         " EXIT SUBROUTINE
sad rlit015
jms rerr                            " ERROR EXIT
dac rop+03                          " PLANT LINK
lac rlink
sad rlkbeg
jms rerr
tad rlit014
dac rlink
jmp i rop+03                        " EXIT
" GARBAGE COLLECTOR - COMBINED PHASE 1 AND 2
rgind=rop+07                        " INDEX NAMES
rgbug=rop 010
rgstkp=rop+011                      " BRANCH STACK POINTER
rgtemp=rop 012
" NOTE THAT THE BRANCH STACK STORES GBUG
rlim: 0                             " HERE IF FREELIST EXPIRED
lac rtop+01
dac rgstkp
lac rbot
dac rgind
jmp rlim1
" LOOP INSPECTING P. NAMES
rlim2: isz rgind                    "  NEXT PERM NAME
"  ---- scan page 118 ----
lac rgind
sad rtop+01
jmp rgarb                           "  TO LAST PHASE IF DONE ALL P NAMES
rlim1: lac i rgind                  "  PICK UP P NAME
dac rgbug
jmp rgntr
" MAIN RECURSIVE ROUTINE
rgbrnch: lac rgstkp
sad rtop
jms rerr                            " BRANCH STACK EXPIRED
rmk1: lac rgbug
dac i rgstkp
isz rgstkp
rgntr: dac rgtemp                   " INITIAL ENTRY
lac i rgbug                         " "CAR"
dac rgbug
rgb2: lac i rgbug                   " AND MOVE TO ITEM
sma
jmp rgitem                          " JUMP IF ITEM
and rlit022
dac rgbug
lac i rgbug
spa
jmp .-04                            " REPEAT WHILE NONITEM
lac i rgtemp
and rlit013                         " RSP BITS
spa                                 " JUMP IF ITEM
tad rlit012                         " MARK IF NONITEM
tad rgbug                           " NB GBUG MUST BE CLEAN HERE
dac i rgtemp                        " SO SKIP REDUNDANT NONITEMS
rgitem: lac i rgbug
and rlit011
sad rlit015
jmp rgnil                           " JMP IF NIL
lac i rgbug
rtl
szl cml                             " PREPARE TO MARK
jmp rgbrtn                          " EXIT IF MARKED ALREADY
rtr                                 " NOW MARK
dac i rgbug
and rlit010
sad rlit021
jmp rgbrtn                          " EXIT IF BLOCK DATA
sza                                 " JUMP IF ATOM
jmp rgbrnch                         " RECURSE IF LIST POINTER
rgbcdr: isz rgbug                   " "CDR"
lac rgbug
dac rgtemp
jmp rgb2                            " REPEAT
" FOUND 1ST NIL
rgnil: tad rlit012
dac i rgbug                         " MARK IT
"  ---- scan page 119 ----
isz rgbug
lac rgbug
sad rend
jmp rgbrtn
lac i rgbug
sad rlit015
tad rlit012                         " MARK SND NIL
dac i rgbug
" EXIT RECURSIVE ROUTINE
rgbrtn: lac rgstkp
sad rtop+01
jmp rlim2                           " FINAL EXIT
tad rlit014                         " -1
dac rgstkp
lac i rgstkp
dac rgbug                           " RECOVER GBUG
jmp rgbcdr                          " CARRY ON
" GARBAGE COLLECTOR PHASE THREE
rgarb:                              " COLLECT GARBAGE & RESTORE LISTS
lac rbeg
dac rop+07                          " START ADDRESS
dzm rop+011                         " CONSECUTIVE INDICATOR ZERO
lac i rop+07
and rlit007                         " TO ALLOW FOR BLOCK DATA
sad rlit007
jms rgbd
sad rlit021                         " TO ALLOW FOR DEAD BLOCK DATA
jms rgbd1
ral
sma
jmp .+011                           " JUMP FIRST GARBAGE ITEM
lac i rop+07
and rlit011
dac i rop+07                        " RESTORE LIST ITEM
isz rop+07
lac rop+07                          " ADVANCE ADDRESS
sad rend
jms rerrgb                          " EXIT NO GARBAGE TO COLLECT
rgarb1: jmp .-020                   " LOOP
lac rop+07
dac rfree                           " START NEW FREE LIST
dac rop 010
lac rend
tad rlit006
dac i rop+07                        " ATTACH TERMINAL WORD
isz rop+07
lac rop+07                          " ADVANCE ADDRESS
sad rend
jmp .+025                           " EXIT
lac i rop+07
and rlit007                         " TO ALLOW FOR BLOCK DATA
sad rlit007
jms rgbd
sad rlit021                         " TO ALLOW FOR DEAD BLOCK DATA
"  ---- scan page 120 ----
jms rgbd1
ral
sma
jmp . 04                            " JUMP GOT MORE GARBAGE
lac i rop+07
and rlit011
jmp .-020                           " RESTORE LIST ITEM AND LOOP
lac rop+07
tad rlit006
dac i rop 010                       " COLLECT A WORD
and rlit022
isz rop 010
sad rop 010
isz rop+011
jmp .-033                           " LOOP
lac rop+011
sna
jms rerrgb                          " ERROR EXIT IF NONE CONSECUTIVE
rgarb2: lac rfree
jmp i rlim                          " OK EXIT
rgbd: 0                             " FOR BLOCK DATA
lac i rop+07
and rlit011
dac i rop+07
and rlit022
dac rop+07                          " MOVE OP+7 TO END OF BLOCK DATA
sad rend
jmp rgarb2-03
lac rgbd
add rlit005                         " RESTART THIS SECTION
dac rgbd
jmp i rgbd
rgbd1: 0                            " TO ELIMINATE DEAD BLOCK DATA
lac rop+07
tad rlit021
tad rlit017
sad i rop+07
jmp i rgbd1
dac rop 012
dzm i rop 012
jmp .-05                            " LOOP FOR FURTHER ITEMS
" BLOCK DATA PRODUCER
rbdn:
0
dzm i rend
dzm rgdm                            " ZERO GARBAGE COLLECTION MARKER
tad rlit017
dac rop 02                          " NO OF CONSECUTIVE WORDS NEEDED
xct i rbdn
dac rop+04
lac i rop+04
dac rop+04
lac rfree
rbdc: dac rop+03
dzm rbcc                            " ZERO COUNT
sma
"  ---- scan page 121 ----
tad rlit006
dac rop+011
isz rbcc
lac rbcc                            " COUNT OF CONSECUTIVE WORDS FOUND
sad rop 02
jmp rbdo                            " CORRECT NO FOUND
lac i rop+011
isz rop+011
sad rop+011
jmp .-07                            " IF FREE LIST CONSECUTIVE
sma
jmp rbde                            " FREE LIST EXHAUSTED
lac rop+011
add rlit004
dac rop 010
lac i rop 010
jmp rbdc                            " BEGIN SEARCH AGAIN
rbde: lac rgdm
sza
jms rerrgb                          " CANNOT PRODUCE BLOCK DATA
isz rgdm
dzm i rop+04                        " THROW AWAY OLD ITEMS
jms rlim                            " GARBAGE COLLECT
jmp rbdc
rbdo: lac i rop+011
sma
jmp rbde                            " TRYING TO USE I END
lac rop+03                          " ADDRESS OF FIRST OF CONSECUTIVE WORDS
spa
jmp rbdr                            " FREE LIST NOT INITIALLY CONSECUTIVE
add rlit006
dac rop+03
lac i rop+011
and rlit022
dac rfree                           " RESET FREE LIST
jmp rbdr+02
rbdr: lac i rop+011
dac i rop 010                       " JOIN FREE LIST ROUND BLOCK DATA
lac rop+03
xor rlit016                         " CONVERT TO ADDRESS TYPE
dac i rop+04                        " SET POINTER TO BLOCK DATA MARKER
lac rop+011
tad rlit003                         " BLOCK DATA MARKER IS J02
dac i rop+03                        " SET BLOCK DATA MARKER
and i+jms+rbdn
" RING STRUCTURE PROCESSOR     MAY 1969
rfel:
0                                   " FORM ELEMENT LENGTH ONE
cla
jms rfeln
jmp i rfel
rfeln:
"  ---- scan page 122 ----
0                                   " FORM ELEMENT LENGTH N
cma
dac rop 02                          " SET HEAD COUNTER
law rnm                             " FOR PRINTNAME
jms rgetsp
law rel                             " FOR ELEMENT
jms rgetsp
dac rel1                            " SAVE HEAD ADDRESS
law rel
jms rnullr
jms rcdr
isz rop 02
jmp .-03                            " FORM HEADER
lac rnm
xor rlit002
dac i rel                           " ATNAME
lac rel
dac i rnm                           " BACK POINTER
law rel
jms rcdr
lac rel1
dac i rel
jmp i rfeln
rnullr:
0                                   " FORM NULL RING
jms rop-05
tad rlit001                         " SET RINGSTART
dac i rop+01
lac rop
jmp i rnullr
rinsrt:
0                                   " INSERT Q IN RING P
jms rop-05                          " GET Q
dac rop 02
xct i rinsrt
jms rop-05                          " GET P
lac i rop+01
and rlit000                         " MAY BE RINGSTART
dac i rop 02
lac i rop+01
and rlit001                         " PRESERVE IF RINGSTART
tad rop 02
dac i rop+01                        " JOIN UP
jmp i rinsrt
rfinds:
0                                   " FIND RINGSTART
jms rop-05
dac i rop                           " MOVE NAME
lac i rop+01
and rlit001
sza
"  ---- scan page 123 ----
jmp . 03                            " POINTER ON RINGSTART
lac i rop+01
jmp rop-02                          " LOOP
lac rop
jmp i rfinds                        " EXIT
rfindn:
0                                   " FIND NAME OF ELEMENT
jms rop-05
lac i rop+01
and rlit016                         " TEST IF ATOM
sna
jmp .+04
lac rop
jms rcdr                            " NEXT
jmp .-06                            " LOOP
lac rop
jmp i rfindn                        " EXIT
rfindp: 0                           "  MOVE TO TOP OF HEAD IF ON ATNAME
jms rop-05
lac rlit015
and i rop+01
sna
jmp .+03                            "  IF ATNAME
lac rop
and i+jms+rfindp
lac rop
jms rcdr
jms rcar
and i+jms+rfindp
"  GO ROUND HEAD FINDING NEXT ADDRESS AFTER APPLYING FUNCTION.
"  MOVE X TO NEXT ITEM IN HEAD AND IF RS EXECUTE F1, IF RP EXECUTE F2.
"  CALL BY LAW GRHA; ENTER; LAW X; LAW F1; LAW F2
rgrha: xct i renter                 "  PICK UP X
jms rop-05
dac rop+03                          "  GET CONTENTS OF X
lac i rop+03
and rlit015
sna
jmp .+06                            "  IF ON ATNAME
lac rop
rgr1: jms rcdr
lac rop+01
sad rop+03
jmp rexit                           "  IF BACK TO STARTING-POINT
lac rop
jms rfindp
lac rop+01
"  ---- scan page 124 ----
sad rop+03
jmp rexit
isz renter                          "  MOVE TO F1
law
and i rop+01
sad rlit015
isz renter                          "  MOVE TO F2 IF RINGPOINTER
jms rlktest
lac rop+03
dac i rlink                         "  KEEP STARTING-POINT
xct i renter                        "  PICK UP
jms renter                          "    AND EXECUTE FUNCTION
lac i rlink
dac rop+03                          "  PICK UP STARTING-POINT
clc
tad rlink
dac rlink
lac i rlink
dac renter
xct i renter                        " AND X
jmp rgr1
"  GO ROUND RING FINDING NEXT ADDRESS BEFORE APPLYING FUNCTION.
"  STORE CAR(X), EXECUTE F, AND THEN SET X TO STORED VALUE.
"  CALL AS FOR GRRA.
rgrrb: xct i renter                 "  X
jms rcar                            "  MISS THIS ONE
lac rop+01
dac rop+03                          "  CONTENTS OF X
rgr2: law
and i rop+03
sad rlit002
jmp rexit
law rop+03
jms rcar
jms rlktest
lac rop+03
dac i rlink
isz renter
xct i renter
jms renter
lac i rlink
dac rop+03
clc
tad rlink
dac rlink
lac i rop+03
spa
jmp rexit                           "  IF HAS BEEN DELETED
lac i rlink
dac renter
xct i renter
dac rop
lac rop+03
dac i rop
"  ---- scan page 125 ----
jmp rgr2
rlktest: 0                          " TEST IF ROOM ON LINK STACK
isz rlink
lac rlink
sad rlkend
jms rerr
rlkerr: jmp i rlktest
" RSP ROUTINES FOR USE WITHOUT QUALIFIERS
raddw:
0                                   " ADDWORD IN ELEMENT
dac rop 02
jms rfindn
jms rcdr
lac rop+01                          " HEAD POINTER
dac rop+03                          " HEAD
law rel
jms rgetsp                          " FOR NEW RING ITEM
lac i rop+03
xor rlit016
dac i rop+06                        " CHAIN TO TOP OF HEAD
lac rop+01
dac i rop+03                        " RESET HEAD POINTER
dac i rop 02                        " NAME ON NEW WORD
tad rlit001
dac i rel                           " FORM NULL RING
lac rop 02
jmp i raddw
rdson:
0                                   " DELETE A SON RING
dac rop+04
jms rfinds                          " IN CASE OF WRONG ENTRY
law rgrrb
jms renter
lac rop+04
law .+03
jms renter                          " DO ALSO FOR RING-START
and i+jms+rdson
lac rop+04
jms rpop
jmp rexit
rdelb:
0                                   " DELETE ELEMENT FROM BROTHER RING
jms rop-05
dac rop+03
lac i rop+01
"  ---- scan page 126 ----
and rlit001                         " TEST IF RINGSTART
sza
jmp i rdelb                         " EXIT IF ILLEGAL
lac i rop+01
jms rcar+07
dac rop 02                          " MOVE TO NEXT IN RING
lac i rop+01
jms rcar+07
sad rop+03                          " DOES THIS POINT BACK TO THE ORIGINAL ELEMENT
skp
jmp .-05
lac i rop 02
and rlit001                         " PRESERVE IF RING START
tad i rop+03
dac i rop 02                        " DELETE POINTER
lac rop
jms rpop
jmp i rdelb
" pause
" variable beg
" variable free
" variable endres
" variable bot
" variable top
" variable savins
" variable lpbeg
" variable lop
" variable lkbeg
" variable link
" variable el
" variable el1
" variable nm
" variable savsub
" variable point
" variable line
" variable sbpi
" variable inst
" variable pbdm
" variable symb
" variable note
" variable errmeb
" variable end
" variable lkend
" variable errgb
" variable gdm
" variable bcc
"  ---- scan page 127 ----

" variables, in order of first use
rbeg: 0
rfree: 0
rendres: 0
rbot: 0
rtop: 0
rsavins: 0
rlpbeg: 0
rlop: 0
rlkbeg: 0
rlink: 0
rel: 0
rel1: 0
rnm: 0
rsavsub: 0
rpoint: 0
rline: 0
rsbpi: 0
rinst: 0
rpbdm: 0
rsymb: 0
rnote: 0
rerrmeb: 0
rend: 0
rlkend: 0
rerrgb: 0
rgdm: 0
rbcc: 0
" literals
rlit000: 0117777                    " (117777
rlit001: 040000                     " (40000
rlit002: 0140000                    " (140000
rlit003: 0420001                    " (420001
rlit004: -02                        " (-1
rlit005: -05                        " (-4
rlit006: 0400000                    " (400000
rlit007: 0220000                    " (220000
rlit010: 0560000                    " (560000
rlit011: 0577777                    " (577777
rlit012: 0200000                    " (200000
rlit013: 0760000                    " (760000
rlit014: 0777777                    " (777777
rlit015: 0100000                    " (100000
rlit016: 0500000                    " (500000
rlit017: 01                         " (1
rlit020: 077777                     " (77777
rlit021: 020000                     " (20000
rlit022: 017777                     " (17777
rlit023: 0400001                    " (400001
